# config/paperclip.yml
common: &common
  :styles:
    :thumb: "50x50#"
    :small: "80x80#"
    :medium: "200x150#"
    :normal: "320x240#"
    :large: "800x600#"
  :default_url: "/images/default_image.png"


development:
  <<: *common

production:
  <<: *common
  :storage: :s3
  :bucket: "kenstagram"
  :path: "/:class/:attachment/:id_partition/:style/:filename"
  :s3_host_name: "s3-website-ap-southeast-1.amazonaws.com"

test:
  <<: *common